# Generated by Django 3.2.3 on 2021-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210606_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/no-image.png', upload_to='profile/%Y/%m-%d'),
        ),
    ]
