# Generated by Django 3.2.3 on 2021-06-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210602_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pseudonym',
            field=models.CharField(default='Benihime', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='iakdnisd', unique=True),
            preserve_default=False,
        ),
    ]
