# Generated by Django 3.2.3 on 2021-06-06 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Book Genre Name')),
                ('is_important', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Book Type')),
            ],
            options={
                'verbose_name': 'Book type',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Book Cycle Name')),
                ('desciption', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Book Cycle Creator')),
            ],
            options={
                'verbose_name': 'Book Cycle',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images/%Y-%m-%d/')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Book Name')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('remark', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('F', 'Finished'), ('D', 'Draft'), ('N', 'Not finished')], default='N', max_length=2)),
                ('is_introductory', models.BooleanField(default=False)),
                ('is_eighteen_plus', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('can_comment', models.CharField(choices=[('A', 'All'), ('O', 'Only friends'), ('N', 'Nobody')], default='N', max_length=2)),
                ('can_read', models.CharField(choices=[('A', 'All'), ('O', 'Only friends'), ('N', 'Nobody')], default='N', max_length=2)),
                ('can_download', models.CharField(choices=[('A', 'All'), ('O', 'Only friends'), ('N', 'Nobody')], default='N', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.cycle', verbose_name='Book Cycle')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.genre', verbose_name='Genre of the book')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.type', verbose_name='Book Type')),
            ],
            options={
                'verbose_name': 'Book Info',
                'verbose_name_plural': 'Books Info',
            },
        ),
    ]
