# Generated by Django 3.2.3 on 2021-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='images/no-image.jpg', upload_to='images/%Y-%m-%d/'),
        ),
    ]
