# Generated by Django 3.2.3 on 2021-05-30 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210530_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.cycle', verbose_name='Book Cycle'),
        ),
    ]
