# Generated by Django 3.2.3 on 2021-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
