# Generated by Django 3.2.3 on 2021-06-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_view_counts_book_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='desciption',
            new_name='description',
        ),
    ]
