# Generated by Django 3.2.3 on 2021-06-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_desciption_cycle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.cycle', verbose_name='Book Cycle'),
        ),
    ]
