# Generated by Django 3.2.3 on 2021-06-02 12:15

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
