# Generated by Django 3.2.3 on 2021-06-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
    ]
