# Generated by Django 3.2.3 on 2021-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='dsaidj'),
            preserve_default=False,
        ),
    ]
