# Generated by Django 3.2.3 on 2021-06-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
