# Generated by Django 3.2.3 on 2021-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_delete_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('D', 'Draft'), ('N', 'Not finished')], default='N', max_length=2),
        ),
    ]
