# Generated by Django 3.2.3 on 2021-06-04 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='account.customuser', verbose_name='Book Cycle Creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='desciption',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
