# Generated by Django 3.2.3 on 2021-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=2),
        ),
    ]
